from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, HTTPException, Request

router = APIRouter(prefix="/api/story", tags=["Story"])


def _get_state(request: Request, run_id: Optional[str]) -> dict:
    orch = request.app.state.orchestrator
    rid = run_id or orch.latest_run_id()
    if not rid:
        raise HTTPException(status_code=404, detail="No pipeline runs found.")
    state = orch.get_state(rid)
    if not state:
        raise HTTPException(status_code=404, detail=f"Run '{rid}' not found.")
    if state.get("status") not in ("done", "running"):
        raise HTTPException(status_code=202, detail=f"Run status: {state.get('status')}")
    return state


@router.get("")
async def get_story(request: Request, run_id: Optional[str] = None):
    """Full chapter-by-chapter narrative generated by the StoryAgent."""
    state = _get_state(request, run_id)
    story = state.get("story", {})
    if not story:
        status = state.get("status", "unknown")
        code = 202 if status == "running" else 404
        raise HTTPException(status_code=code, detail="Story not ready yet — pipeline still running." if status == "running" else "No story available. Run the pipeline first.")
    return story


@router.get("/one-liner")
async def get_one_liner(request: Request, run_id: Optional[str] = None):
    """Single executive-summary sentence from the StoryAgent."""
    state = _get_state(request, run_id)
    story = state.get("story", {})
    one_liner = story.get("one_liner", "")
    if not one_liner:
        raise HTTPException(status_code=404, detail="No story one-liner available.")
    return {"one_liner": one_liner}


@router.get("/chapter/{chapter_key}")
async def get_chapter(chapter_key: str, request: Request, run_id: Optional[str] = None):
    """Return a specific story chapter by key.

    Known keys: chapter_1_data_overview, chapter_2_what_we_checked,
    chapter_3_wow_moments, chapter_4_what_to_do, one_liner
    """
    state = _get_state(request, run_id)
    story = state.get("story", {})
    if not story:
        raise HTTPException(status_code=404, detail="No story available. Run the pipeline first.")
    if chapter_key not in story:
        raise HTTPException(
            status_code=404,
            detail=f"Chapter '{chapter_key}' not found. Available keys: {list(story.keys())}",
        )
    return {chapter_key: story[chapter_key]}
