pipeline {
    agent any

    environment {
        APP_NAME = '4sight-app'
        CONTAINER_NAME = '4sight-container'
        APP_PORT = '8010'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Show Workspace') {
            steps {
                bat 'cd'
                bat 'dir'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %APP_NAME% .'
            }
        }

        stage('Stop Old Container') {
            steps {
                bat 'docker rm -f %CONTAINER_NAME% || exit 0'
            }
        }

        stage('Run 4sight Container') {
            steps {
                bat '''
                docker run -d --name %CONTAINER_NAME% ^
                  -p %APP_PORT%:%APP_PORT% ^
                  %APP_NAME%
                '''
            }
        }

        stage('Health Check') {
            steps {
                bat 'curl http://localhost:8010/docs'
            }
        }

        stage('Verify Metrics') {
            steps {
                bat 'curl http://localhost:8010/metrics'
            }
        }

        stage('List Containers') {
            steps {
                bat 'docker ps'
            }
        }
    }

    post {
        success {
            echo '4sight deployed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
            bat 'docker logs %CONTAINER_NAME%'
        }
    }
}